- src/main/java/fr/xephi/authme/listener/AuthMeEntityListener.java
Right now players can hit other players before logging in, causing serious issues with plugins like CombatTag, PvPManager etc.
We should cancel this in a simple EntityDamageByEntity listener.
Did not test the code.
> Cancel damage if unlogged-in player is attacking other entities

- src/main/java/fr/xephi/authme/datasource/MySQLThread.java
username_clean
PhpBB3 requires second column (username_clen) with username as table primary key. Yet, config value "mySQLOtherUsernameColumns" is not an option as this value needs to be formated with phpBB custom utf8_clean_string() function which brings letters to lower case, merges nearby spaces and removes invalid UTF8 chatacters.
Due to characters already being limited both in config and in minecraft itself I believe toLowerCaste() will suffice for now.
num_users
Increment users count not to loose those nice statistics!
> Fix for phpBB3 support + bonus

- src/main/java/fr/xephi/authme/cache/limbo/LimboCache.java
When #addLimboPlayer(Player player) is called, the player is put into the list with his real name, but when #getLimboPlayer(String name) is called, its looking for the lowercased name, causing a NullPointerException
> Fix NPE when onPlayerJoins occurs

- README.md
- src/main/java/fr/xephi/authme/commands/ChangePasswordCommand.java
- src/main/java/fr/xephi/authme/process/join/AsyncronousJoin.java
- src/main/java/fr/xephi/authme/process/login/AsyncronousLogin.java
More details inside commit descriptions.
Also, I'd like to suggest a new feature:
If someone has an unsafe password, or password=username, or password < minLenght, or password > maxLenght, or password contains "where", "delete", etc, or password doesn't match pass REG_EX, then the player is logged in, but is forced to use /changepassword oldPass newPass to change is password to a safer one in order to play again.
> Email recall at login, typo fix and ChangePassword Enhancements

- src/main/resources/config.yml
We are now allowing every ASCII character except for space (0x20 - 32). Those are the characters allowed in passwords.
Note: You may want to check if in config a single slash is OK for excluding a character, or if we need 2 like in the code.
> Enhanced Password Regex

- docs/hash_algorithms.md
- pom.xml
- src/main/java/fr/xephi/authme/security/HashAlgorithm.java
- src/main/java/fr/xephi/authme/security/crypts/Argon2.java
- src/test/java/fr/xephi/authme/security/crypts/Argon2Test.java
> Implement ARGON2 hash

- docs/commands.md
- docs/permission_nodes.md
- src/main/java/fr/xephi/authme/command/CommandInitializer.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/CountryLookup.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/DataStatistics.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/DebugCommand.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/DebugSection.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/HasPermissionChecker.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/InputValidator.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/LimboPlayerViewer.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/PermissionGroups.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/PlayerAuthViewer.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/SpawnLocationViewer.java
- src/main/java/fr/xephi/authme/command/executable/authme/debug/TestEmailSender.java
- src/main/java/fr/xephi/authme/permission/DebugSectionPermissions.java
- src/main/java/fr/xephi/authme/permission/PlayerStatePermission.java
- src/main/resources/plugin.yml
- src/test/java/fr/xephi/authme/command/executable/authme/debug/DebugCommandTest.java
- src/test/java/fr/xephi/authme/command/executable/authme/debug/HasPermissionCheckerTest.java
- src/test/java/fr/xephi/authme/permission/AbstractPermissionsEnumTest.java
- src/test/java/fr/xephi/authme/permission/AdminPermissionTest.java
- src/test/java/fr/xephi/authme/permission/DebugSectionPermissionsTest.java
- src/test/java/fr/xephi/authme/permission/PermissionConsistencyTest.java
- src/test/java/fr/xephi/authme/permission/PlayerPermissionTest.java
- src/test/java/fr/xephi/authme/permission/PlayerStatePermissionTest.java
- src/test/java/tools/docs/permissions/PermissionNodesGatherer.java
- src/test/java/tools/filegeneration/GeneratePluginYml.java
I would like to close #1034 after this—this PR adds better permissions for the individual debug sections. I added the permissions in a separate class.
- Add an individual permission for each debug section (including wildcard perm)
- Create test for DebugCommand
- Refactor tests for the enum permission nodes to use the same abstract class
- Update related project files (plugin.yml, permission docs, command docs)
> #1034 Create permissions for debug sections

- docs/commands.md
- docs/config.md
- docs/permission_nodes.md
- src/main/java/fr/xephi/authme/command/CommandInitializer.java
- src/main/java/fr/xephi/authme/command/executable/email/ShowEmailCommand.java
- src/main/java/fr/xephi/authme/permission/PlayerPermission.java
- src/main/java/fr/xephi/authme/settings/properties/SecuritySettings.java
- src/main/resources/plugin.yml
- src/test/java/fr/xephi/authme/command/executable/email/ShowEmailCommandTest.java
Now the command `/email show` requires the permission: `"authme.player.email.see"` and will return a partially hidden email.
E.g.
normal: `my.email@example.com`
hidden: `my.*****@***ple.com`
format: `1/3(id lenght) + *** + @ + *** + 2/3(domain lenght)`
> #1119 email show permission and privacy improvements

- src/main/java/fr/xephi/authme/datasource/MySQL.java
- src/main/java/fr/xephi/authme/datasource/MySqlMigrater.java
- src/main/java/fr/xephi/authme/datasource/SqLiteMigrater.java
Last change before #792 can be verified / closed ;)
On MySQL some time before 5.2 the last IP column was initialized as `NOT NULL` but no default value was provided. Now that we don't set a "last IP" value upon registration the database is unhappy. This is the same migration as we already do it in SQLite, so it's good for both to behave similarly.
If the column is required to be NOT NULL (forum integrations), this can be switched again with `/authme debug mysqldef`, which will add the last IP column as NOT NULL incl. a default value.
Given the amount of "migration code" I decided to move all of the MySQL migrations into their own class. Didn't create a common type with the SQLiteMigrater because they don't have much in common but if you feel it would be sensible, we can talk about it. ;)
> #792 Migrate last IP column if is NOT NULL without default value

- .travis.yml
- pom.xml
- src/main/java/fr/xephi/authme/security/crypts/Pbkdf2Django.java
- src/test/java/fr/xephi/authme/AuthMeInitializationTest.java
- src/test/java/fr/xephi/authme/command/executable/email/SetPasswordCommandTest.java
- src/test/java/fr/xephi/authme/service/RecoveryCodeServiceTest.java
Java 9 removed the DatatypeConvert class and so I replaced it with the Base64 class which was introduced in Java 8. 
While working on that I discovered some issues with the Tests which were reproducible on [Travis](https://travis-ci.org/AuthMe/AuthMeReloaded/jobs/294205481). Suprisingly they occured only Java 9 which could be a bug in the Mockito implementation. 
1. AuthMeInitializationTest.initAuthMe NPE when accessing the mocked Logger [in PluginLogger of Bukkit](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/plugin/PluginLogger.java#L26) 
Fix:
Change to anonymous logger
https://github.com/AuthMe/AuthMeReloaded/blob/d9b53f08b129ab8b1e8292d5999d3b4705d93b6e/src/test/java/fr/xephi/authme/AuthMeInitializationTest.java#L78
2. …
> Fix Java 9 support for Pbkdf2Django

- docs/config.md
- samples/NewConfig.yml
- src/main/java/fr/xephi/authme/initialization/OnStartupTasks.java
- src/main/java/fr/xephi/authme/settings/properties/SecuritySettings.java
- src/test/resources/fr/xephi/authme/config.test.yml
- src/test/resources/fr/xephi/authme/settings/config-old.yml
This is a security plugin and given it's purpose, having a simple option to show in plain text every password while instead there's no PLAINTEXT store option in the database (not anymore, as last time we discussed about this option there was still many refactoring to do), is stupid and unsafe.
Many people use this option more for bad than for good, probably no one will ever complain about this providing a good use case.
Latest step in security would be a way to encrypt or hide commands to command loggers, but this may be impossible with Bukkit API.
> Improve security of Console and Log files

- src/main/java/fr/xephi/authme/AuthMe.java
- src/main/java/fr/xephi/authme/initialization/SettingsProvider.java
- src/main/java/fr/xephi/authme/service/yaml/YamlFileResourceProvider.java
- src/main/java/fr/xephi/authme/service/yaml/YamlParseException.java
- src/main/java/fr/xephi/authme/settings/commandconfig/CommandManager.java
- src/main/java/fr/xephi/authme/util/ExceptionUtils.java
- src/test/java/fr/xephi/authme/service/yaml/YamlFileResourceProviderTest.java
- src/test/java/fr/xephi/authme/util/ExceptionUtilsTest.java
- src/test/resources/fr/xephi/authme/service/yaml/invalidYaml.yml
- src/test/resources/fr/xephi/authme/service/yaml/validYaml.yml
Impl for #1497.
- Wrap SnakeYAML exceptions when loading config.yml and commands.yml on startup into own exception type
- Handle exception type on startup with specific error message
> #1497 Show specific message for invalid YAML files

- pom.xml
- src/main/java/fr/xephi/authme/message/Messages.java
By setting a unique Tag (%username%), we can replace it with the sender's name inside the Send function.
This pull closes #829.
Some thoughts:
- It won't check for a Player instance, so even Console and Admin commands will replace it with the sender's name, if any. (I think Console gives an UUID or "ConsoleSender" as his name).
- Since Admin commands aren't yet translated, part of the above thought can be ignored for now.
- By setting it as a "special" tag, like %nl%, it is different than specific single message tags that only have 1 % at the beginning. This however may cause confusion (for example with the "%name" tag), we should add a comment line inside every translation stating which are the global replaceble tags and what they do.
> Be able to replace sender name in every message

- src/main/resources/plugin.yml
Closes #1040.
I think this is the best solution, better than implementing a case to not kick anyone when an OP player joins.
There's Essentials and other plugins for allowing more people than maximum slots.
> Remove VIP status to OP by default

- README.md
- pom.xml
- src/main/java/fr/xephi/authme/AuthMe.java
- src/main/java/fr/xephi/authme/service/GeoIpService.java
- src/main/java/fr/xephi/authme/settings/properties/ProtectionSettings.java
- src/test/java/fr/xephi/authme/service/GeoIpServiceTest.java
As mentioned in ticket #1471 , MaxMind will stop updating the GEO IP database in April.
Copied from the commit message:
* Update MaxMind database dependency and add javatar to extract the database from the tar archive
(now only a small difference in jar file size)
* Verify downloaded archive using MD5 (There are no other checksums available)
* Migrated to Java NIO instead of old java file I/O (Feedback?)
* Internal Optional usage for nullable values (Feedback?)
* Changed the DatabaseReader at MaxMind to use an interface. This allows us to mock the final class.
* File modification date represents the last time the database was updated at MaxMind.
Minor:
* Change all links of MaxMind to https
* Schedule a Bukkit async task instead of creating a thread manually
* Validate IP input string
* …
> Migrate to GEO IP 2 (Related #1471)

- src/main/java/fr/xephi/authme/security/HashUtils.java
- src/main/java/fr/xephi/authme/security/crypts/BCrypt2y.java
- src/main/java/fr/xephi/authme/security/crypts/Joomla.java
- src/main/java/fr/xephi/authme/security/crypts/Md5vB.java
- src/main/java/fr/xephi/authme/security/crypts/PhpBB.java
- src/main/java/fr/xephi/authme/security/crypts/SeparateSaltMethod.java
- src/main/java/fr/xephi/authme/security/crypts/Sha256.java
- src/main/java/fr/xephi/authme/security/crypts/Smf.java
- src/main/java/fr/xephi/authme/security/crypts/UnsaltedMethod.java
- src/main/java/fr/xephi/authme/security/crypts/UsernameSaltMethod.java
- src/main/java/fr/xephi/authme/security/crypts/Wbb4.java
- src/main/java/fr/xephi/authme/security/crypts/Wordpress.java
- src/main/java/fr/xephi/authme/security/crypts/XAuth.java
- src/test/java/fr/xephi/authme/security/HashAlgorithmIntegrationTest.java
- src/test/java/fr/xephi/authme/security/HashUtilsTest.java
Fix for #1561, basically just replaces `String#equals` calls with a wrapped call to `MessageDigest#isEqual`. I'd be open to a more specific name than `isEqual` to convey the method's very specific intention but everything I came up with sounded... clunky.
cc: @nolleryc
> #1561 Fix timing attacks by comparing hashes in constant time

- docs/permission_nodes.md
- src/main/java/fr/xephi/authme/listener/PlayerListener.java
- src/main/java/fr/xephi/authme/permission/PlayerStatePermission.java
- src/main/resources/plugin.yml
- src/test/java/fr/xephi/authme/listener/PlayerListenerTest.java
I went with a positive permission node (having this permission _allows_ you to chat) because it makes more sense IMHO. 
I think having permission nodes for such features is the way to go for the future. A lot of our configurations could eventually be replaced with permissions and it would offer better control to the server admins. The only downside is that the config is outside of our reach so we can't really perform any migrations on our permission nodes or anything (whereas we fully control our config.yml).
> #1417 Add permission node to allow chat before login

- src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java
- src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java
- src/main/java/fr/xephi/authme/process/register/AsyncRegister.java
- src/main/java/fr/xephi/authme/util/InternetProtocolUtils.java
- src/test/java/fr/xephi/authme/process/login/AsynchronousLoginTest.java
- src/test/java/fr/xephi/authme/util/InternetProtocolUtilsTest.java
* Replace magic values like 127.0.0.1 and use our utility
* Support for IPv6 local adresses in IPv6 only or dual stack environments
* Loopback [::1]
* Site-Local fc00::/7
* Link-local fe80::/10
For site-local I had to introduce a workaround, because Java only checks for deprecated site-local addresses. 
Furthermore I added some documentation that should clear some things up. Reference comments in cd4693eedf60878b184144a8dbdf27d2443fe726.
> Add IPv6 support for isLocal checks

- docs/permission_nodes.md
- src/main/java/fr/xephi/authme/permission/PlayerStatePermission.java
- src/main/java/fr/xephi/authme/process/login/ProcessSyncPlayerLogin.java
- src/main/resources/plugin.yml
Based on issue #1623 I created a permission to allow administrators to bypass the bungeecord server teleportation after login.
The permission is **authme.bypassbungeesend**
> Create permission to bypass bungeecord server teleportation

- src/main/java/fr/xephi/authme/command/executable/authme/VersionCommand.java
We can't just skip from 2017 to 2019.
> Update the copyright year to 2018 just in time.

- src/main/resources/messages/messages_nl.yml
I also added two notes for the next translator about difficult to translate messages.
Should we translate `captcha` to `puzzel` (which means `puzzle` in English)? `captcha` is not really a well-known word in Dutch.
> Updated messages_nl.yml with missing translations.

- docs/config.md
- src/main/java/fr/xephi/authme/service/GeoIpService.java
- src/main/java/fr/xephi/authme/settings/properties/ProtectionSettings.java
- src/test/java/fr/xephi/authme/service/GeoIpServiceTest.java
Now GeoIp database updates require a ClientID and a LicenseKey, which can be obtained for free at https://www.maxmind.com/en/accounts/current/license-key
> Update the GeoIp database download method [BREAKING]

- src/main/java/fr/xephi/authme/api/v3/AuthMeApi.java
No API method was written when the feature was introduced, there are some use-cases where this data is needed.
> Add method to get the registration date to the API

- src/main/java/fr/xephi/authme/api/v3/AuthMeApi.java
- src/main/java/fr/xephi/authme/api/v3/AuthMePlayer.java
- src/main/java/fr/xephi/authme/api/v3/AuthMePlayerImpl.java
- src/test/java/fr/xephi/authme/api/v3/AuthMeApiTest.java
- src/test/java/fr/xephi/authme/api/v3/AuthMePlayerImplTest.java
Introduces an API method to get a lot of player info with one load from the database. Unit tests will still follow but I open this PR early to get some feedback on the naming (and anything else). Ideally we won't have to remove or rename anything in the future since this is an API so it's really worth looking at our API methods carefully.
For the naming of _AuthMePlayer_: "ApiPlayer" would make sense for us in _our_ codebase but not for anyone that is integrating our API. I also chose "Player" over "User" as I guess that's really the more used terminology in Minecraft (you have _players_ on the server; it's _players_ who register themselves in AuthMe).
cc: @RikoDEV @YellowZaki
> #1448 Create AuthMePlayer to get player data from API with

- src/main/java/fr/xephi/authme/listener/PlayerListener.java
UNRESTRICTED_INVENTORIES is a lowercase string set, so the inventory title also needs to be converted to lowercase in order to be able to match the inventory names specified in the config
> Unrestricted inventories fix

- src/main/resources/messages/help_cz.yml
- src/main/resources/messages/messages_cz.yml
Hello!
It's Hacktoberfest time again and I would like to contribute to AuthMeReloaded with localization to my native language.
In this pull request, I have:
- translated all the TODO resource strings 
- added help_cz localization file and translated all the resource strings contained
- unified the voice, or tone, which is used in both localization files; before this update, there was a mix up of the second case singular and second place plural when addressing a user of the plugin. I unified it to use 2nd case singular.
As time is of the essence in regards to Hacktoberfest, it would be greatly appreciated if you could merge my PR as soon as possible.
Thanks and keep up the good work!
> Get Czech localizations to 100%

- docs/config.md
- src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
AuthMeReloaded already registers the `/log` command by default. Then this command cannot be used **after** the user logs in (which of course is good), but the same command cannot be used **before** the user logs in as well, which makes this particular command completely useless (by default of course, without modifying the config file).
My commit resolves this situation by adding the `/log` command to the default `allowCommands` sequence so that from now on this command can be used alongside the `/login` and `/l` commands.
> Addition of /log command in the allowCommands sequence

- src/main/java/fr/xephi/authme/settings/SpawnLoader.java
Technical information available in the last comments of the issue,  here's a recap:
When Spigot (in my case Tuinity) calls the PlayerQuitEvent, it returns a Player instance which is flagged as both dead and offline. When AuthMeReloaded saves the quit location it checks for those two values, which return garbage data. A quick and easy way to check if the Player was dead at the moment of the quit is to check it's health, which is exactly what I did. The health value is fortunately reliable and shows 0.0 if the player was dead on exit
The exploit that could take place before this fix:
If you selected "Go to title screen" upon death and rejoined the server you could "bypass" your respawn location and directly spawn on the location of your death. I've tested my fix and it works!
> Fix #2018. using player's health value instead of isDead (unreliable)

- src/main/java/fr/xephi/authme/settings/properties/HooksSettings.java
Based on the discussion #2356, there was the suggestion to raise the default BCrypt cost factor. This is necessary to accommodate todays increased computing power with the goal to slow down brute force attempts against leaked databases.
Notes:
* BCrypt is insecure against massively parallel GPU hashing, ASICS and FPGA (low memory requirements)
* Cost factor is a user configurable setting
* BCrypt is not our default algorithm
* Default in other software:
* PHP: 10
* Some Rust crates: 12
* Ruby: 12
* Golang: 10
Benchmark (JMH) from our BCrypt library with i7700k:
https://github.com/patrickfav/bcrypt#performance
|              | cost 6   | cost   8  | cost 10  | cost 12   | cost 14   |
|--------------|----------|-----------|----------|-----------|-----------|
| jBcrypt      |  3.43 ms | …
> [Discussion] Raise BCrypt default cost factor for current computing power

- src/main/java/fr/xephi/authme/datasource/SQLite.java
When OP customize bukkit/spigot plugins directory location, SQLite file will still on default directory.
It will cause directory not found exception. Also let SQLite file not correct in the plugin directory.
for example, my server use following script to execute server
```sh
SERVER_DIR="$(dirname "$PWD")"
PLUGIN_DIR="${SERVER_DIR}/plugins"
CONFIG_DIR="${SERVER_DIR}/configs"
WORLD_DIR="${SERVER_DIR}/worlds"
cd "${CONFIG_DIR}/vanilla"
java \
-Dlog4j.configurationFile="${CONFIG_DIR}/log4j2.xml" \
-server \
-jar "${SERVER_DIR}/server.jar" \
--plugins $PLUGIN_DIR \
--world-dir $WORLD_DIR \
--bukkit-settings "${CONFIG_DIR}/spigot/bukkit.yml" \
--spigot-settings "${CONFIG_DIR}/spigot/spigot.yml" \
--commands-settings "${CONFIG_DIR}/spigot/commands.yml" \
--nogui
```
Our directory structure is as …
> Fix SQLite file not found issue

- src/test/java/fr/xephi/authme/listener/PlayerListenerTest.java
A flaky test is found in this project and this PR proposes to fix it.
1. How to reproduce the flaky test
- The project is built and tested under `javaJDK8`.
- The tool used for the flaky test detection is [NonDex](https://github.com/TestingResearchIllinois/NonDex).
- I ran `mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=fr.xephi.authme.listener.PlayerListenerTest#shouldHideChatFromUnauthed`, which produces
`PlayerListenerTest.shouldHideChatFromUnauthed:348 
Expected: iterable containing [<Mock for Player, hashCode: 775174220>, <Mock for Player, hashCode: 810672306>]
but: item 0: was <Mock for Player, hashCode: 810672306>`.
2. Why the test failed
- The method `org.bukkit.event.player.AsyncPlayerChatEvent.getRecipients()` called in the test …
> fix a flaky test 

- src/main/java/fr/xephi/authme/process/Management.java
- src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java
- src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java
- src/main/java/fr/xephi/authme/service/bungeecord/BungeeReceiver.java
Presently when AuthMeBungee is used and requireAuth is set to true a player needs to login before doing anything.
This will allow players who are not registered (have no password) to be treated as if they are logged in by broadcasting the LOGIN message.
This means that players who are registered will be required to login and will be unable to execute any command either on the server or on the proxy, and those who are not registered will still be able to play without needing to register.
> If a player is not registered then we send a LOGIN plugin message on join

- src/main/java/fr/xephi/authme/service/bungeecord/BungeeReceiver.java
- src/main/java/fr/xephi/authme/settings/SettingsWarner.java
This PR added a simple check that check spigot.yml -> settings.bungeecord status by using AuthMe built-in method bukkitService.isBungeeCordConfiguredForSpigot() and disable hook if it enabled and not behind an BungeeCord proxy.
Register plugin message channel without BungeeCord proxy will allow attacker send fake login payload to treat AuthMe login with Plugin Message for him and bypass the user login.
Fixed:
https://github.com/AuthMe/AuthMeReloaded/issues/2571
https://github.com/AuthMe/AuthMeReloaded/issues/2559
> Execute simple check before enable BungeeCord hook.

- .github/workflows/maven.yml
This runs the the Maven workflow for pull requests targeting the main branch too. This can be useful to verify if the actually compiles and the test runs. 
However GitHub has bug/logic error that configurations like in this PR runs twice, because `push` and `pull_request` triggers for internal branches.
See this for reference:
https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
> Run workflows for pull requests too to verify the test results

- src/test/java/fr/xephi/authme/api/v3/AuthMeApiTest.java
Hey 😊
I want to contribute the following test:
Test that `result.getLastLoginTime("notAPlayer")` is null when `getLastLoginTime` is called with the parameter `playerName = "notAPlayer"`.
This tests the method [`AuthMeApi.getLastLoginMillis`](https://github.com/AuthMe/AuthMeReloaded/blob/3892bb692354d4591aac023f5eb05f68466c8353/src/main/java/fr/xephi/authme/api/v3/AuthMeApi.java#L202).
This test is based on the test [`shouldReturnInstanceOrNull`](https://github.com/AuthMe/AuthMeReloaded/blob/3892bb692354d4591aac023f5eb05f68466c8353/src/test/java/fr/xephi/authme/api/v3/AuthMeApiTest.java#L75).
Curious to hear what you think!
Also, is the description I provided of the test is helping you to answer to this pull request? Why (not)?
(I wrote this test as part of a research study at TU Delft. …
> Add test for AuthMeApi.getLastLoginMillis

- src/main/java/fr/xephi/authme/datasource/AbstractSqlDataSource.java
- src/main/java/fr/xephi/authme/datasource/DataSourceType.java
- src/main/java/fr/xephi/authme/datasource/MariaDB.java
- src/main/java/fr/xephi/authme/datasource/MySQL.java
- src/main/java/fr/xephi/authme/datasource/PostgreSqlDataSource.java
- src/main/java/fr/xephi/authme/datasource/SQLite.java
- src/main/java/fr/xephi/authme/initialization/DataSourceProvider.java
Trying to use this plugin with MariaDB, I got exceptions related to `MySQL.isColumnMissing` (error report below), 
I do not have MySQL for the test, but https://github.com/AuthMe/AuthMeReloaded/issues/2543 shows the same error on MySQL
This PR fixes it
```
[12:01:12 WARN]: [AuthMe] Can't initialize the MySQL database: [SQLSyntaxErrorException]: Unknown column 'x' in 'authme'
[12:01:12 WARN]: [AuthMe] Please check your database settings in the config.yml file!
[12:01:12 WARN]: [AuthMe] Could not create data source: [SQLSyntaxErrorException]: Unknown column 'x' in 'authme'
[12:01:12 WARN]: [AuthMe] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[12:01:12 WARN]: java.lang.IllegalStateException: Error during initialization of data source …
```
> Add support MariaDB driver & fix MySQL column check; 

- .checkstyle.xml
Not ideal but better than nothing :)
> Add Checkstyle rule to disallow toLowerCase() and toUpperCase() without Locale

- src/main/java/fr/xephi/authme/service/AntiBotService.java
I was wondering why the automatic antibot never triggered no matter what settings I used.
So after doing some debugging and testing with some bots on a local server, looks like it was a pretty simple mistake.
The counter interval should be a value in miliseconds instead of seconds so it was never counting up (unless bots joined under 5 miliseconds). So it should actually work now.
> Fix automatic antibot

- src/main/java/fr/xephi/authme/process/login/ProcessSyncPlayerLogin.java
- src/main/java/fr/xephi/authme/service/TeleportationService.java
- src/test/java/fr/xephi/authme/service/TeleportationServiceTest.java
This pull request resolves #2723.
- Save a quit location before first login teleport
- Removed y = 0 check in TeleportationService
- Removed y coordinate validation test, since y coordinate is always set
This fix works fine in my own fork and no bugs found(currently)
> Fix y = 0 teleportUnAuthedToSpawn bug
