pom.xml
Sorry, earlier I sent you a pull with Mutliverse-INVENTORIES Lol.
This is Multiverse-Core with scope defined. ;)
=> Fixed Multiverse scope

src/main/resources/messages/messages_br.yml
=> Update brazilian messages

src/main/java/fr/xephi/authme/events/PasswordEncryptionEvent.java, src/main/java/fr/xephi/authme/security/PasswordSecurity.java, src/main/java/fr/xephi/authme/settings/properties/SecuritySettings.java, src/test/java/fr/xephi/authme/security/HashAlgorithmIntegrationTest.java, src/test/java/fr/xephi/authme/security/PasswordSecurityTest.java
- Avoid creating the same object over and over; instead keep it and only change it on settings reload
=> #1188 Create and keep encryption method instance

src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandConfig.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandManager.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandSettingsHolder.java, src/main/resources/commands.yml, src/test/java/fr/xephi/authme/settings/commandconfig/CommandManagerTest.java, src/test/resources/fr/xephi/authme/settings/commandconfig/commands.complete.yml
#1090 
Needs test methods, @ljacqu any advice?
=> Implement onSessionLogin trigger for commands.yml

src/main/java/fr/xephi/authme/command/executable/authme/debug/LimboPlayerViewer.java, src/main/java/fr/xephi/authme/data/limbo/AuthGroupHandler.java, src/main/java/fr/xephi/authme/data/limbo/LimboPlayer.java, src/main/java/fr/xephi/authme/data/limbo/LimboServiceHelper.java, src/main/java/fr/xephi/authme/data/limbo/persistence/LimboPlayerDeserializer.java, src/main/java/fr/xephi/authme/data/limbo/persistence/LimboPlayerSerializer.java, src/main/java/fr/xephi/authme/permission/PermissionsManager.java, src/test/java/fr/xephi/authme/data/limbo/LimboPlayerMatchers.java, src/test/java/fr/xephi/authme/data/limbo/LimboPlayerTaskManagerTest.java, src/test/java/fr/xephi/authme/data/limbo/LimboServiceHelperTest.java, src/test/java/fr/xephi/authme/data/limbo/LimboServiceTest.java, src/test/java/fr/xephi/authme/data/limbo/persistence/DistributedFilesPersistenceHandlerTest.java, src/test/java/fr/xephi/authme/data/limbo/persistence/IndividualFilesPersistenceHandlerTest.java, src/test/resources/fr/xephi/authme/data/limbo/seg16-8-limbo.json
=> Store the entire player's list of groups instead of primary group

src/main/resources/messages/messages_pl.yml
I could do it before, I'll do it now. 👍
=> Small fixes in Polish translation and addition of missing colors.

docs/config.md, src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
hi @sgdc3,
per our discussion. :) My proposition based on your input.
=> Make default regex for password characters more user-friendly

src/main/java/fr/xephi/authme/service/ValidationService.java, src/test/java/fr/xephi/authme/service/ValidationServiceTest.java
=> Implement restricted users rules with * wildcard support 

docs/permission_nodes.md, src/main/java/fr/xephi/authme/listener/OnJoinVerifier.java, src/main/java/fr/xephi/authme/listener/PlayerListener.java, src/main/java/fr/xephi/authme/permission/PlayerStatePermission.java, src/main/resources/plugin.yml, src/test/java/fr/xephi/authme/listener/OnJoinVerifierTest.java, src/test/java/fr/xephi/authme/listener/PlayerListenerTest.java
#1321 Still need to fix unit tests
=> Add permission to bypass country check

src/main/resources/messages/help_ro.yml
Translated /authme help in romanian.
=> Translated /authme help in romanian.

src/main/java/fr/xephi/authme/api/v3/AuthMeApi.java, src/main/java/fr/xephi/authme/command/executable/authme/ChangePasswordAdminCommand.java, src/main/java/fr/xephi/authme/process/Management.java, src/main/java/fr/xephi/authme/process/changepassword/AsyncChangePassword.java, src/test/java/fr/xephi/authme/api/v3/AuthMeApiTest.java, src/test/java/fr/xephi/authme/command/executable/authme/ChangePasswordAdminCommandTest.java, src/test/java/fr/xephi/authme/process/changepassword/AsyncChangePasswordTest.java
=> API: Implement changePassword method

docs/commands.md, src/main/java/fr/xephi/authme/command/CommandInitializer.java, src/main/java/fr/xephi/authme/command/executable/authme/MessagesCommand.java, src/main/java/fr/xephi/authme/command/help/HelpMessage.java, src/main/java/fr/xephi/authme/command/help/HelpMessagesService.java, src/main/java/fr/xephi/authme/command/help/HelpSection.java, src/main/java/fr/xephi/authme/service/HelpTranslationGenerator.java, src/main/java/fr/xephi/authme/service/JoinMessageService.java
Implement '/authme messages help' to generate a fully complete help text file
If either of you has time to review, please do :)
=> #1338 Implement '/authme messages help'

src/main/java/fr/xephi/authme/AuthMe.java, src/main/java/fr/xephi/authme/command/executable/authme/ReloadCommand.java, src/main/java/fr/xephi/authme/settings/SettingsWarner.java, src/test/java/fr/xephi/authme/command/executable/authme/ReloadCommandTest.java, src/test/java/fr/xephi/authme/settings/SettingsWarnerTest.java
=>  #1190 Show settings warnings on reload also

src/main/java/fr/xephi/authme/command/executable/authme/debug/CountryLookup.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/DataStatistics.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/DebugCommand.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/HasPermissionChecker.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/InputValidator.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/LimboPlayerViewer.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/MySqlDefaultChanger.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/PermissionGroups.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/PlayerAuthViewer.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/SpawnLocationViewer.java, src/main/java/fr/xephi/authme/command/executable/authme/debug/TestEmailSender.java, src/test/java/fr/xephi/authme/command/executable/authme/debug/DataStatisticsTest.java, src/test/java/fr/xephi/authme/command/executable/authme/debug/DebugCommandTest.java
Some improvements on the `/authme debug` front ;) The two commits contain more detailed information.
=> Improve MySQL not null toggle / authme debug commands output

docs/config.md, src/main/java/fr/xephi/authme/listener/JoiningPlayer.java, src/main/java/fr/xephi/authme/listener/OnJoinVerifier.java, src/main/java/fr/xephi/authme/listener/PlayerListener.java, src/main/java/fr/xephi/authme/permission/PermissionsManager.java, src/main/java/fr/xephi/authme/settings/properties/PluginSettings.java, src/test/java/fr/xephi/authme/listener/OnJoinVerifierTest.java, src/test/java/fr/xephi/authme/listener/PlayerListenerTest.java, src/test/java/fr/xephi/authme/permission/PermissionsManagerTest.java
- Introduce new configuration (as done by @sgdc3)
- Create JoiningPlayer, based on a Player object or String name, determining how permissions will be checked
This is a rival to https://github.com/AuthMe/AuthMeReloaded/pull/1395 ;) lol
=> #1350 Add option to force using the sync PlayerLoginEvent

src/main/java/fr/xephi/authme/AuthMe.java, src/main/java/fr/xephi/authme/command/executable/authme/PurgeLastPositionCommand.java, src/main/java/fr/xephi/authme/initialization/OnShutdownPlayerSaver.java, src/main/java/fr/xephi/authme/listener/PlayerListener.java, src/main/java/fr/xephi/authme/process/changepassword/AsyncChangePassword.java, src/main/java/fr/xephi/authme/process/email/AsyncAddEmail.java, src/main/java/fr/xephi/authme/process/email/AsyncChangeEmail.java, src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java, src/main/java/fr/xephi/authme/process/login/ProcessSyncPlayerLogin.java, src/main/java/fr/xephi/authme/process/logout/AsynchronousLogout.java, src/main/java/fr/xephi/authme/process/quit/AsynchronousQuit.java, src/main/java/fr/xephi/authme/process/register/AsyncRegister.java, src/main/java/fr/xephi/authme/process/register/ProcessSyncPasswordRegister.java, src/main/java/fr/xephi/authme/process/unregister/AsynchronousUnregister.java, src/main/java/fr/xephi/authme/service/bungeecord/BungeeReceiver.java, src/main/java/fr/xephi/authme/service/bungeecord/BungeeSender.java, src/main/java/fr/xephi/authme/service/bungeecord/BungeeService.java, src/main/java/fr/xephi/authme/service/bungeecord/MessageType.java, src/test/java/fr/xephi/authme/AuthMeInitializationTest.java, src/test/java/fr/xephi/authme/command/executable/authme/PurgeLastPositionCommandTest.java, src/test/java/fr/xephi/authme/process/changepassword/AsyncChangePasswordTest.java, src/test/java/fr/xephi/authme/process/email/AsyncAddEmailTest.java, src/test/java/fr/xephi/authme/process/email/AsyncChangeEmailTest.java, src/test/java/fr/xephi/authme/process/unregister/AsynchronousUnregisterTest.java
There is a failing test due to cyclic dependency injection, @ljacqu could you take a quick look at this?
=> Implement AuthMeBungee autologin

src/main/resources/messages/messages_es.yml
=> Translate Email Verification messages.

src/main/java/fr/xephi/authme/service/BukkitService.java, src/main/java/fr/xephi/authme/service/bungeecord/BungeeSender.java
=> Do not use Bukkit#sendPluginMessage

src/main/java/fr/xephi/authme/command/CommandInitializer.java, src/main/java/fr/xephi/authme/command/executable/authme/RecentPlayersCommand.java, src/main/java/fr/xephi/authme/datasource/CacheDataSource.java, src/main/java/fr/xephi/authme/datasource/DataSource.java, src/main/java/fr/xephi/authme/datasource/FlatFile.java, src/main/java/fr/xephi/authme/datasource/MySQL.java, src/main/java/fr/xephi/authme/datasource/SQLite.java, src/main/java/fr/xephi/authme/permission/AdminPermission.java, src/main/resources/plugin.yml, src/test/java/fr/xephi/authme/command/executable/authme/RecentPlayersCommandTest.java, src/test/java/fr/xephi/authme/datasource/AbstractDataSourceIntegrationTest.java
Impl for #1254 because I really want this
- Create datasource method to fetch most recent players by last login date
- Add command to view last logged in players
=> #1254 Create command to see recently logged in players

src/main/java/fr/xephi/authme/process/SyncProcessManager.java, src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java, src/main/java/fr/xephi/authme/process/login/ProcessSyncPlayerLogin.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandConfig.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandManager.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandMigrationService.java, src/main/java/fr/xephi/authme/settings/commandconfig/CommandSettingsHolder.java, src/main/resources/commands.yml, src/test/java/fr/xephi/authme/settings/commandconfig/CommandManagerTest.java, src/test/resources/fr/xephi/authme/settings/commandconfig/commands.complete.yml
- Allow to configure commands run on player's first login (login of player with a previously null lastlogin date)
Impl for #1046
=> #1046 Add onFirstLogin to commands.yml

src/main/resources/messages/messages_hu.yml
TODO-s have been deleted and translated.
=> Updated messages_hu.yml file to the latest version

src/main/java/fr/xephi/authme/command/executable/email/RecoverEmailCommand.java, src/test/java/fr/xephi/authme/command/executable/email/RecoverEmailCommandTest.java
Haven't been able to test this in-game. I'll do it tomorrow. If someone wants to have a look at the code until then, please do :)
=> #1435 Send password recovery emails in async

src/main/resources/messages/messages_it.yml
I'm 2 months late... so embarassing 😳
=> [Messages_IT] Translate new messages

src/main/resources/messages/messages_ko.yml
=> Korean Translation

src/main/java/fr/xephi/authme/permission/PlayerStatePermission.java
I haven't dig enough inside the source code of the new AuthMe and so I always forget about tests.
=> Fix last commit

src/main/java/fr/xephi/authme/service/BukkitService.java, src/main/java/fr/xephi/authme/settings/SettingsWarner.java, src/main/java/fr/xephi/authme/util/Utils.java, src/test/java/fr/xephi/authme/settings/SettingsWarnerTest.java
Moved the logic for Spigot to BukkitService so the method can be mocked
=> #1531 Move spigot detection to BukkitService

src/main/resources/messages/messages_pt.yml
I'm not sure of this translation.
=> Translation messages_pt.yml

src/main/resources/messages/messages_id.yml
Some word has been corrected to proper Indonesian language
=> Improving Indonesian translations

src/main/java/fr/xephi/authme/listener/PlayerListener.java, src/main/java/fr/xephi/authme/settings/properties/RestrictionSettings.java
=> #1655 Implements whitelist for inventories interactions

src/main/resources/messages/messages_zhhk.yml
Cuz chinese font in Minecraft sucks, and those characters somehow will stick with each other, making the sentence very hard to read. This PR is to fix the problem and add some color code to the commands.
=> Fix Chinese font issue

src/main/java/fr/xephi/authme/security/totp/GenerateTotpService.java, src/main/java/fr/xephi/authme/security/totp/TotpAuthenticator.java, src/test/java/fr/xephi/authme/security/totp/GenerateTotpServiceTest.java, src/test/java/fr/xephi/authme/security/totp/TotpAuthenticatorTest.java
- Make TotpAuthenticator keep track of the used codes and reject any known ones
I took the cheap way and didn't introduce a new message for an expired code :P
=> #1219 Make 2FA tokens one-use only

src/main/java/fr/xephi/authme/data/auth/PlayerAuth.java, src/main/java/fr/xephi/authme/datasource/AbstractSqlDataSource.java, src/main/java/fr/xephi/authme/datasource/Columns.java, src/main/java/fr/xephi/authme/datasource/MySQL.java, src/main/java/fr/xephi/authme/datasource/PostgreSqlDataSource.java, src/main/java/fr/xephi/authme/datasource/SQLite.java, src/main/java/fr/xephi/authme/datasource/columnshandler/AuthMeColumns.java, src/main/java/fr/xephi/authme/datasource/converter/LoginSecurityConverter.java, src/main/java/fr/xephi/authme/process/register/executors/PlayerAuthBuilderHelper.java, src/main/java/fr/xephi/authme/settings/properties/DatabaseSettings.java, src/main/java/fr/xephi/authme/util/UuidUtils.java
=> Feat #1813 : Add optional column for players uuids

src/main/java/fr/xephi/authme/settings/SpawnLoader.java
=> Improves spawn choice if undefined

src/main/resources/messages/help_fr.yml
=> One mistake corrected

src/main/resources/messages/help_et.yml, src/main/resources/messages/messages_et.yml
Reordered and improved some strings.
=> Estonian improvements

src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java
Implemented functionality of enhancement issue #2064
Before (Player registers)
After (Player registers)
=> Add player's IP into login logger (#2064)

samples/website_integration/AuthMeController.php
Added password change function to AuthMe php controller.
This can help if you want to release password changing in your server's website.
=> Added password change

src/main/java/fr/xephi/authme/datasource/MySQL.java, src/main/java/fr/xephi/authme/settings/properties/DatabaseSettings.java
TODO: Configurable Driver Class Name
=> Specify the Driver Class Name ("com.mysql.cj.jdbc.Driver")

src/main/java/fr/xephi/authme/data/limbo/persistence/LimboPlayerSerializer.java
=> Fix java 16 compatibility issue (#2341)

pom.xml
Fixes LibertyBans plugin startup.
=> Relocate mariadb jdbc

src/main/resources/messages/messages_lt.yml
Fixed some typo's and finished translating
=> Finished translating messages_lt.yml

src/main/resources/messages/messages_vn.yml
Fixed some typo's and finished translating
=> Finished translating messages_vn.yml

docs/config.md, src/main/java/fr/xephi/authme/service/GeoIpService.java, src/main/java/fr/xephi/authme/settings/properties/ProtectionSettings.java, src/test/java/fr/xephi/authme/service/GeoIpServiceTest.java
=> Config option to disable GeoIP database

pom.xml
This pull request update postgresql to 42.7.2
=> Update PostgreSQL to resolve CVE-2024-1597
